export const navigation = [
    {
      id: "0",
      title: "Features",
      url: "#features",
    },
    {
      id: "1",
      title: "Pricing",
      url: "#pricing",
    },
    {
      id: "2",
      title: "How to use",
      url: "#how-to-use",
    },
    {
      id: "3",
      title: "Roadmap",
      url: "#roadmap",
    },
    {
      id: "4",
      title: "New account",
      url: "#signup",
      onlyMobile: true,
    },
    {
      id: "5",
      title: "Sign in",
      url: "#login",
      onlyMobile: true,
    },
  ];
  


export const articles = [
    {
      id: 1,
      image: 'https://via.placeholder.com/300', 
      author: 'John Doe',
      avatar: 'https://via.placeholder.com/30', 
      timePosted: '4 hours ago',
      title: 'Breaking News: Major Event Happening Today',
      content: 'Officials are preparing for a major event happening later todayStay healthy during the summer months with these essential tips',
      category: 'Politics',
      readTime: '6 min read',
    },
    {
      id: 2,
      image: 'https://via.placeholder.com/300',
      author: 'Jane Smith',
      avatar: 'https://via.placeholder.com/30',
      timePosted: '2 hours ago',
      title: 'New Discovery in the Tech World',
      content: 'A groundbreaking new technology has just been unveiledStay healthy during the summer months with these essential tips',
      category: 'Technology',
      readTime: '4 min read',
    },
    {
      id: 3,
      image: 'https://via.placeholder.com/300',
      author: 'Mike Johnson',
      avatar: 'https://via.placeholder.com/30',
      timePosted: '1 hour ago',
      title: 'Sports Championship Finals Tonight',
      content: 'The championship finals are scheduled for tonightStay healthy during the summer months with these essential tips',
      category: 'Sports',
      readTime: '5 min read',
    },
    {
      id: 4,
      image: 'https://via.placeholder.com/300',
      author: 'Emily Davis',
      avatar: 'https://via.placeholder.com/30',
      timePosted: '30 minutes ago',
      title: 'Health Tips for you during the Summer',
      content: 'Stay healthy during the summer months with these essential tipsStay healthy during the summer months with these essential tipsStay healthy during the summer months with these essential tips',
      category: 'Health',
      readTime: '3 min read',
    },
  ];
  

  export const article = {
    id: 1,
    image: 'https://via.placeholder.com/600x400',
    avatar: 'https://via.placeholder.com/40',
    author: 'John Doe',
    timePosted: '4 hours ago',
    title: 'Breaking News: Something Important Happened Today',
    content: 'This is a summary of the article content. Officials have said something, and the world is reacting his is a summary of the article content. Officials have said something, and the world is reacting his is a summary of the article content. Officials have said something, and the world is reacting',
    category: 'News',
    readTime: 3,
  };


  export const news = [
    {
      id: 1,
      image: 'https://via.placeholder.com/300',
      author: 'John Doe',
      avatar: 'https://via.placeholder.com/30',
      timePosted: '4 hours ago',
      title: 'Breaking News: Major Event Happening Today',
      content: 'Officials are preparing for a major event happening later today...',
      category: 'Politics',
      readTime: '6 min read',
    },
    {
      id: 2,
      image: 'https://via.placeholder.com/300',
      author: 'Jane Smith',
      avatar: 'https://via.placeholder.com/30',
      timePosted: '2 hours ago',
      title: 'New Discovery in the Tech World',
      content: 'A groundbreaking new technology has just been unveiled...',
      category: 'Technology',
      readTime: '4 min read',
    },
    {
      id: 3,
      image: 'https://via.placeholder.com/300',
      author: 'Mike Johnson',
      avatar: 'https://via.placeholder.com/30',
      timePosted: '1 hour ago',
      title: 'Sports Championship Finals Tonight',
      content: 'The championship finals are scheduled for tonight...',
      category: 'Sports',
      readTime: '5 min read',
    },
    {
      id: 4,
      image: 'https://via.placeholder.com/300',
      author: 'Emily Davis',
      avatar: 'https://via.placeholder.com/30',
      timePosted: '30 minutes ago',
      title: 'Health Tips for the Summer',
      content: 'Stay healthy during the summer months with these essential tips...',
      category: 'Health',
      readTime: '3 min read',
    },
    {
      id: 5,
      image: 'https://via.placeholder.com/300',
      author: 'Sarah Lee',
      avatar: 'https://via.placeholder.com/30',
      timePosted: '3 hours ago',
      title: 'Economic Growth Surges This Quarter',
      content: 'The economy has shown tremendous growth in the last quarter...',
      category: 'Business',
      readTime: '7 min read',
    },
    {
      id: 6,
      image: 'https://via.placeholder.com/300',
      author: 'David Clark',
      avatar: 'https://via.placeholder.com/30',
      timePosted: '6 hours ago',
      title: 'Top 10 Travel Destinations for 2024',
      content: 'Explore the top travel destinations for the upcoming year...',
      category: 'Travel',
      readTime: '5 min read',
    },
    {
      id: 7,
      image: 'https://via.placeholder.com/300',
      author: 'Laura Wilson',
      avatar: 'https://via.placeholder.com/30',
      timePosted: '5 hours ago',
      title: 'How to Manage Stress at Work',
      content: 'Effective strategies for managing stress in the workplace...',
      category: 'Lifestyle',
      readTime: '4 min read',
    },
    {
      id: 8,
      image: 'https://via.placeholder.com/300',
      author: 'Mark Thompson',
      avatar: 'https://via.placeholder.com/30',
      timePosted: '8 hours ago',
      title: 'Global Climate Change Updates',
      content: 'The latest updates on global climate change and its impacts...',
      category: 'Environment',
      readTime: '6 min read',
    },
    {
      id: 9,
      image: 'https://via.placeholder.com/300',
      author: 'Anna Green',
      avatar: 'https://via.placeholder.com/30',
      timePosted: '1 day ago',
      title: 'New Culinary Trends for 2024',
      content: 'Discover the top culinary trends expected to dominate next year...',
      category: 'Food',
      readTime: '5 min read',
    },
    {
      id: 10,
      image: 'https://via.placeholder.com/300',
      author: 'James Brown',
      avatar: 'https://via.placeholder.com/30',
      timePosted: '2 days ago',
      title: 'Advancements in Renewable Energy',
      content: 'How renewable energy sources are transforming the future...',
      category: 'Technology',
      readTime: '7 min read',
    },
    {
      id: 11,
      image: 'https://via.placeholder.com/300',
      author: 'Paul Roberts',
      avatar: 'https://via.placeholder.com/30',
      timePosted: '1 week ago',
      title: 'New Legislation Passed in Parliament',
      content: 'A new set of laws was passed in parliament this week...',
      category: 'Politics',
      readTime: '8 min read',
    },
    {
      id: 12,
      image: 'https://via.placeholder.com/300',
      author: 'Maria Gonzalez',
      avatar: 'https://via.placeholder.com/30',
      timePosted: '3 days ago',
      title: 'Famous Actor Announces Retirement',
      content: 'A legendary actor announced their retirement from the big screen...',
      category: 'Entertainment',
      readTime: '3 min read',
    },
    {
      id: 13,
      image: 'https://via.placeholder.com/300',
      author: 'Chris Evans',
      avatar: 'https://via.placeholder.com/30',
      timePosted: '12 hours ago',
      title: 'Cybersecurity Threats on the Rise',
      content: 'New cybersecurity threats have emerged recently...',
      category: 'Technology',
      readTime: '6 min read',
    },
    {
      id: 14,
      image: 'https://via.placeholder.com/300',
      author: 'Olivia White',
      avatar: 'https://via.placeholder.com/30',
      timePosted: '5 hours ago',
      title: 'Meditation Techniques for Inner Peace',
      content: 'Explore meditation techniques to achieve inner calm and peace...',
      category: 'Wellness',
      readTime: '4 min read',
    },
    {
      id: 15,
      image: 'https://via.placeholder.com/300',
      author: 'William King',
      avatar: 'https://via.placeholder.com/30',
      timePosted: '2 weeks ago',
      title: 'New Educational Reforms Announced',
      content: 'The government announced major reforms in the education sector...',
      category: 'Education',
      readTime: '7 min read',
    },
    {
      id: 16,
      image: 'https://via.placeholder.com/300',
      author: 'Sophia Harris',
      avatar: 'https://via.placeholder.com/30',
      timePosted: '9 hours ago',
      title: 'Fashion Trends for the Winter Season',
      content: 'Discover the hottest fashion trends for the upcoming winter...',
      category: 'Fashion',
      readTime: '5 min read',
    },
    {
      id: 17,
      image: 'https://via.placeholder.com/300',
      author: 'Michael Cooper',
      avatar: 'https://via.placeholder.com/30',
      timePosted: '10 minutes ago',
      title: 'Stock Market Hits Record High',
      content: 'The stock market has reached new record highs today...',
      category: 'Finance',
      readTime: '6 min read',
    },
    {
      id: 18,
      image: 'https://via.placeholder.com/300',
      author: 'Isabella Parker',
      avatar: 'https://via.placeholder.com/30',
      timePosted: '7 days ago',
      title: 'How to Start a Successful Business',
      content: 'Key tips for starting and managing a successful business...',
      category: 'Business',
      readTime: '8 min read',
    },
    {
      id: 19,
      image: 'https://via.placeholder.com/300',
      author: 'Matthew Harris',
      avatar: 'https://via.placeholder.com/30',
      timePosted: '16 hours ago',
      title: 'The Future of Electric Vehicles',
      content: 'What’s next for electric vehicles and the automotive industry...',
      category: 'Technology',
      readTime: '5 min read',
    },
    {
      id: 20,
      image: 'https://via.placeholder.com/300',
      author: 'Grace Walker',
      avatar: 'https://via.placeholder.com/30',
      timePosted: '1 month ago',
      title: 'Art Exhibition Showcases Local Talent',
      content: 'A new art exhibition is highlighting talented local artists...',
      category: 'Arts',
      readTime: '4 min read',
    },
  ];
  